import test from 'node:test';
import assert from 'node:assert/strict';
import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
async function collectJs(dir){const entries=await readdir(dir,{withFileTypes:true}),files=[];for(const entry of entries){const full=path.join(dir,entry.name);if(entry.isDirectory()){if(entry.name==='node_modules')continue;files.push(...await collectJs(full));}else if(entry.name.endsWith('.js'))files.push(full);}return files;}
const files=await collectJs(root);const sourceEntries=await Promise.all(files.map(async(file)=>[path.relative(root,file).replaceAll('\\','/'),await readFile(file,'utf8')]));const source=sourceEntries.map(([,value])=>value).join('\n');const app=await readFile(path.join(root,'AppRoot.js'),'utf8');
const profileSource=await readFile(path.join(root,'screens/profile.js'),'utf8');
const visualSource=await readFile(path.join(root,'ui/web-visual-source.js'),'utf8');
const accountSource=profileSource.slice(profileSource.indexOf('export function AccountScreen'),profileSource.indexOf('export function ProfileArea'));

test('Mobile is a thin UI/platform layer over alantil-core',()=>{for(const module of ['test','match','favorites','learning-route','word-normalizer','settings','station-test','learning','profile','songs','word-progress','route-progress','sync-policy','dictionary-contract'])assert.match(source,new RegExp(`packages/alantil-core/${module}\\.js`));});
test('Mobile 16.4 runtime dictionary comes from the Web repository contract, not AppRoot starter data',()=>{assert.doesNotMatch(app,/STARTER_DICTIONARY|starter-dictionary\.js/);assert.match(app,/bootstrapNativeDictionary/);const dictionary=sourceEntries.find(([file])=>file==='platform/dictionary.js')?.[1]||'';assert.match(dictionary,/DICTIONARY_CONTENT_TABLE/);assert.match(dictionary,/DICTIONARY_STORIES_TABLE/);assert.match(dictionary,/DICTIONARY_METADATA_TABLE/);for(const [file,content] of sourceEntries){assert.doesNotMatch(content,/const\s+ROWS\s*=|STARTER_DICTIONARY\s*=\s*\[/,`copied dictionary in ${file}`);}});
test('Game and progress business algorithms are not reimplemented inside mobile',()=>{const forbidden=[/function\s+buildTestOptions\s*\(/,/function\s+initializeTestState\s*\(/,/function\s+initializeMatchState\s*\(/,/function\s+recordMatchMismatch\s*\(/,/function\s+buildStationTestSessionState\s*\(/,/function\s+initializeLearnState\s*\(/,/function\s+buildLearningRoute\s*\(/,/function\s+normalizeLegacyWordEntry\s*\(/,/function\s+applyLearnWordResults\s*\(/,/function\s+applyTestWordResults\s*\(/,/function\s+applyMatchWordResults\s*\(/,/function\s+mergeCloudWordProgressState\s*\(/];for(const [file,content] of sourceEntries)for(const pattern of forbidden)assert.doesNotMatch(content,pattern,`business algorithm duplicated in ${file}`);});
test('Mobile has all native adapters and Web-parity screen modules',()=>{const names=new Set(sourceEntries.map(([file])=>file));for(const expected of ['platform/storage.js','platform/auth.js','platform/auth.native.js','platform/auth.web.js','platform/supabase.js','platform/supabase.native.js','platform/supabase.web.js','platform/profile-api.js','platform/progress.js','platform/cloud-sync.js','platform/session-store.js','platform/hidden-words.js','platform/songs.js','platform/dictionary.js','screens/onboarding.js','screens/station.js','screens/learn.js','screens/station-test.js','screens/practice-games.js','screens/profile.js','screens/songs.js','i18n.js','ui/theme.js','ui/components.js','ui/icons.js','ui/modal.js','ui/web-visual-source.js'])assert.ok(names.has(expected),`missing ${expected}`);});
test('Mobile screens do not access Supabase REST directly',()=>{for(const [file,content] of sourceEntries){if(!file.startsWith('screens/'))continue;assert.doesNotMatch(content,/supabase\.co|\/rest\/v1|\/auth\/v1/,`platform access leaked into ${file}`);}});

test('Account uses shared i18n and contains no old hardcoded Russian Account copy',()=>{assert.match(accountSource,/mobileMsg\(language/);for(const text of ['Проверить','Создать профиль','Открываем Google','Не удалось открыть авторизацию','Продолжить с Google','Никнейм соответствует требованиям','Аватар сохранён'])assert.doesNotMatch(accountSource,new RegExp(text),`hardcoded Account copy: ${text}`);});
test('Account matches Web nickname and avatar flow contracts',()=>{assert.match(accountSource,/setTimeout\(async\(\)=>\{[\s\S]*?\},350\)/);assert.match(accountSource,/checkNativeNickname\(validation\.nickname\)/);assert.match(accountSource,/ConfirmDialog/);assert.match(accountSource,/setNativeAvatarGender/);assert.match(profileSource,/getNativeAuthProvider/);assert.match(accountSource,/onGuest/);});
test('AppRoot preserves Profile Account back flow and guest Path flow',()=>{assert.match(app,/onBack=\{\(\)\s*=>\s*setScreen\('home'\)\}/);assert.match(app,/const\s+continueAsGuest\s*=\s*\(\)\s*=>\s*\{[\s\S]*?setTab\('path'\);[\s\S]*?setScreen\('home'\)/);assert.match(app,/settings=\{settings\}\s+onGuest=\{continueAsGuest\}/);});
test('visual manifest audits every required Web shared source',()=>{for(const name of ['theme.css','typography.css','shell.css','chrome.css','components.css','paper-components.css','segmented-control.css','table-system.css','app.css','base.css','reset.css'])assert.match(visualSource,new RegExp(name.replace('.','\\.')));assert.match(visualSource,/WEB_VISUAL_COVERAGE/);assert.match(visualSource,/missingCoverage/);assert.match(visualSource,/UI_TOKENS/);});
