import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { filterSongs, buildSongLyricsModel } from '../../packages/alantil-core/songs.js';
import { normalizeUserSettings, applyUserSettingsUpdate } from '../../packages/alantil-core/settings.js';

const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../..');
const read=(relative)=>fs.readFileSync(path.join(root,relative),'utf8');

test('16.5 Path keeps shared route progress and per-story navigation persistence',()=>{const source=read('mobile/screens/path.js');assert.match(source,/createRouteProgressSnapshot/);assert.match(source,/stationWordProgress/);assert.match(source,/computedStationStatus/);assert.match(source,/loadNativePathSettings/);assert.match(source,/loadNativeStoryScroll/);assert.match(source,/saveNativeActiveStory/);assert.match(source,/saveNativeStoryScroll/);});
test('16.5 Station uses contextual hidden words and launches Learn active words but Stage Test full station',()=>{const source=read('mobile/screens/station.js');assert.match(source,/hiddenContext/);assert.match(source,/loadNativeHiddenWords\(hiddenContext\)/);assert.match(source,/saveNativeHiddenWords\(hiddenContext,\s*next,\s*changed\)/);assert.match(source,/onLearn\(activeWords,\s*direction\)/);assert.match(source,/onTest\(station,\s*direction\)/);});
test('16.5 Learn remains resumable, favorite-aware and progress-backed',()=>{const source=read('mobile/screens/learn.js');assert.match(source,/initializeLearnState/);assert.match(source,/decideLearnCard/);assert.match(source,/undoLearnDecision/);assert.match(source,/loadNativeSessionSnapshot\('learn'\)/);assert.match(source,/saveNativeSessionSnapshot\('learn'/);assert.match(source,/recordNativeLearnSession/);assert.match(source,/toggleFavorite/);});
test('16.5 Stage Test restores and records exact session state',()=>{const source=read('mobile/screens/station-test.js');assert.match(source,/buildStationTestSessionState/);assert.match(source,/stationTestActiveSnapshot/);assert.match(source,/recordNativeTestSession/);assert.match(source,/clearNativeSessionSnapshot\('station-test'\)/);});
test('16.5 Practice General Test and Match keep shared scope, limits and resumable sessions',()=>{const source=read('mobile/screens/practice-games.js');assert.match(source,/buildPracticeScope/);assert.match(source,/scopeSelectionState/);assert.match(source,/scopeSelectionCounts/);assert.match(source,/\[20,\s*40,\s*80\]/);assert.match(source,/initializeTestState/);assert.match(source,/initializeMatchState/);assert.match(source,/loadNativeSessionSnapshot\('test'\)/);assert.match(source,/loadNativeSessionSnapshot\('match'\)/);});
test('16.5 Practice Back saves resumable Test/Match and result flows use real progress recording',()=>{const source=read('mobile/screens/practice-games.js');assert.match(source,/BackHandler\.addEventListener/);assert.match(source,/saveNativeSessionSnapshot\('test'/);assert.match(source,/saveNativeSessionSnapshot\('match'/);assert.match(source,/recordNativeTestSession/);assert.match(source,/recordNativeMatchSession/);assert.match(source,/clearNativeSessionSnapshot\('test'\)/);assert.match(source,/clearNativeSessionSnapshot\('match'\)/);});
test('16.5 Favorites keeps isolated contextual selection and launches the shared learning flow',()=>{const favorites=read('mobile/screens/favorites.js'),app=read('mobile/AppRoot.js'),store=read('mobile/platform/session-store.js');assert.match(favorites,/FAVORITES_HIDDEN_CONTEXT/);assert.match(favorites,/onLearn\(activeRows,\s*direction\)/);assert.match(favorites,/showAll/);assert.match(favorites,/hideAll/);assert.doesNotMatch(favorites,/onMatch/);assert.match(app,/setNativeSessionNamespace\(type,\s*scopeId\)/);assert.match(app,/openPracticeGame\('test',\s*displayWords,\s*'home',\s*'all'\)/);assert.match(app,/openPracticeGame\('match',\s*displayWords,\s*'home',\s*'all'\)/);assert.match(store,/namespaces=new Map/);assert.match(store,/namespace\?`:\$\{namespace\}`:''/);});
test('16.5 Songs search covers title artist lyrics and lyric tokens resolve dictionary words',()=>{const songs=[{id:'1',title:'Тау',artist:'Автор',lyrics:'тау барам',translation:'иду в горы'}];assert.equal(filterSongs(songs,{searchQuery:'тау',searchMode:'title'}).length,1);assert.equal(filterSongs(songs,{searchQuery:'автор',searchMode:'artist'}).length,1);assert.equal(filterSongs(songs,{searchQuery:'барам',searchMode:'lyrics'}).length,1);const dictionary=[{id:'w1',word:'тау',wordAlanCyrillic:'тау',wordAlanTurkic:'taw',trans:'гора'}],model=buildSongLyricsModel('тау барам','гора иду',dictionary);assert.equal(model[0].originalLines[0].tokens.find((token)=>token.token==='тау').word.id,'w1');});
test('16.5 Songs persists search/navigation state and exposes runtime audio errors',()=>{const source=read('mobile/screens/songs.js');assert.match(source,/\[query,\s*setQuery\]\s*=\s*useState\(''\)/);assert.match(source,/\[mode,\s*setMode\]\s*=\s*useState\('title'\)/);assert.match(source,/query=\{query\}\s+mode=\{mode\}/);assert.match(source,/activeSongId/);assert.match(source,/loadNativeSessionSnapshot\('songs-ui'\)/);assert.match(source,/saveNativeSessionSnapshot\('songs-ui'/);assert.match(source,/status\?\.error/);assert.match(source,/buildSongLyricsModel/);});
test('16.5 Profile Statistics Settings are real-data backed and expose all persisted settings plus versions',()=>{const profile=read('mobile/screens/profile-main.js'),progress=read('mobile/platform/progress.js'),storage=read('mobile/platform/storage.js'),app=JSON.parse(read('mobile/app.json')),pkg=JSON.parse(read('mobile/package.json'));assert.match(profile,/getNativeProgressSummary/);assert.match(profile,/loadNativeWordProgressMap/);assert.match(profile,/summary\.activity\?\.sessions/);assert.match(profile,/summary\.difficult/);assert.match(profile,/dictionaryPathProgress/);assert.match(profile,/interface_language_code/);assert.match(profile,/alan_script_code/);assert.match(profile,/alan_dialect_code/);assert.match(profile,/text_size_code/);assert.match(profile,/getNativeDictionaryDiagnostics/);assert.equal(pkg.version,app.expo.version);assert.match(app.expo.version,/^\d+\.\d+\.\d+$/);assert.match(progress,/summarizeWordProgress/);assert.match(progress,/activeSeconds/);assert.match(progress,/sessions/);assert.match(progress,/buildProblemWordRows/);assert.match(storage,/saveNativeSettings/);assert.match(storage,/queuePreferences/);const settings=normalizeUserSettings(applyUserSettingsUpdate({}, {interface_language_code:'tr',alan_script_code:'turkic',text_size_code:'large'}));assert.equal(settings.interface_language_code,'tr');assert.equal(settings.alan_script_code,'turkic');assert.equal(settings.text_size_code,'large');});
test('16.5 Expo Web bootstrap cannot remain permanently on BootScreen after one rejected dependency',()=>{const source=read('mobile/AppRoot.js');assert.match(source,/Promise\.allSettled/);assert.doesNotMatch(source,/Promise\.all\(\[/);assert.match(source,/setBootstrapped\(true\)/);const app=JSON.parse(read('mobile/app.json')),pkg=JSON.parse(read('mobile/package.json'));assert.equal(pkg.version,app.expo.version);assert.match(app.expo.version,/^\d+\.\d+\.\d+$/);assert.equal(app.expo.web.bundler,'metro');});