import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url)),mobile=path.resolve(here,'..'),root=path.resolve(mobile,'..');
const read=(relative)=>fs.readFileSync(path.join(mobile,relative),'utf8'),readRoot=(relative)=>fs.readFileSync(path.join(root,relative),'utf8');
const sharedTokens=fs.readFileSync(path.join(mobile,'../packages/alantil-ui/tokens.js'),'utf8');
const sharedChrome=fs.readFileSync(path.join(mobile,'../packages/alantil-ui/chrome.js'),'utf8');
const visual=read('ui/web-visual-source.js'),parity=read('ui/parity.js'),setPreparation=read('ui/set-preparation.js'),profile=read('screens/profile-main.js'),practice=read('screens/practice.js'),pathScreen=read('screens/path.js'),station=read('screens/station.js'),dictionary=read('platform/dictionary.js'),app=JSON.parse(read('app.json')),pkg=JSON.parse(read('package.json'));
const requiredWebSources=['src/shared/styles/theme.css','src/shared/styles/typography.css','src/shared/styles/shell.css','src/shared/styles/chrome.css','src/shared/styles/components.css','src/shared/styles/paper-components.css','src/shared/styles/segmented-control.css','src/shared/styles/table-system.css','src/features/path/path.css','src/features/profile/profile.css','src/features/settings/settings.css','src/features/practice/practice.css','src/features/learn/learn.css','src/features/test/test.css','src/features/match/match.css','src/features/songs/songs.css','src/features/onboarding/onboarding.css'];

test('16.6 visual manifest covers canonical Web 13.15.12 system and feature sources',()=>{for(const source of requiredWebSources)assert.match(visual,new RegExp(source.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(visual,/WEB_VISUAL_SOURCES\.features/);});
test('Expo Web bundled dictionary is storage-independent',()=>{assert.match(dictionary,/bootstrapDictionaryRuntime/);assert.match(dictionary,/persistSnapshot:\s*writeCache/);assert.match(dictionary,/bundledSnapshot/);assert.match(dictionary,/starterSnapshot/);assert.match(readRoot('packages/alantil-core/dictionary-bootstrap.js'),/void Promise\.resolve\(persistSnapshot\?\.\(bundled\)\)\.catch/);});
test('Settings follows the Web flat-page composition',()=>{for(const token of['settings.nastroyki','settings.sohranit','settings.yazykovye_nastroyki','settings.yazyk_interfeysa','settings.alfavit_alanskih_slov','settings.variant_kirillitsy','settings.versiya_slovarya','settings.tekuschaya','settings.aktualnaya','settings.obnovit','settings.blagodarnosti','settings.versiya_prilozheniya','settings.politika_konfidentsialnosti'])assert.ok(profile.includes(token),token);assert.match(profile,/settingsScroll:\s*\{[^}]*maxWidth:\s*620/s);assert.match(profile,/settingRow:\s*\{[^}]*minHeight:\s*46/s);assert.match(profile,/settingsLearningPreview:\s*\{[^}]*height:\s*180/s);assert.match(profile,/versionFlatRow:\s*\{[^}]*minHeight:\s*42/s);assert.doesNotMatch(profile.slice(profile.indexOf('function SettingsPane'),profile.indexOf('export function ProfileMainArea')),/SurfaceCard/);});
test('Profile uses canonical avatar assets instead of synthetic geometry',()=>{assert.match(profile,/avatar_male\.png/);assert.match(profile,/avatar_female\.png/);assert.doesNotMatch(profile,/avatarHead|avatarBody/);});
test('Practice uses Web flat menu rows and separate panel heading',()=>{assert.match(practice,/<Header title="Alan Til!"/);assert.match(practice,/panelHead/);assert.match(practice,/panelTitle/);assert.match(practice,/ListRow/);assert.doesNotMatch(practice,/\[ ПРАКТИКА \]/i);assert.match(parity,/surfaceFlat:/);});
test('Path and Station preserve canonical route and compact row geometry',()=>{assert.match(pathScreen,/POSITION_PATTERN\s*=\s*\[-1,\s*0,\s*1,\s*0\]/);assert.match(sharedTokens,/scaleDot:4/);assert.match(sharedTokens,/scaleDiamond:9/);assert.match(pathScreen,/scaleDot:\s*\{[^}]*width:\s*theme\.path\.scaleDot[^}]*height:\s*theme\.path\.scaleDot/s);assert.match(pathScreen,/scaleDiamond:\s*\{[^}]*width:\s*theme\.path\.scaleDiamond[^}]*height:\s*theme\.path\.scaleDiamond/s);assert.match(station,/SetPreparationView/);assert.match(setPreparation,/row:\s*\{[^}]*minHeight:\s*52/s);assert.match(station,/mobile\.station\.learn/);assert.match(station,/mobile\.station\.test/);});
test('Set preparation styles initialize before exported reference to avoid Expo Web TDZ crash',()=>{const declaration=setPreparation.indexOf('const styles=StyleSheet.create'),exported=setPreparation.indexOf('export const setPreparationStyles=styles;');assert.ok(declaration>=0,'styles declaration missing');assert.ok(exported>declaration,'setPreparationStyles must be exported only after styles initialization');});
test('16.6.5 version is coherent across Expo and package metadata',()=>{assert.equal(app.expo.version,'16.6.6');assert.equal(pkg.version,'16.6.6');assert.equal(app.expo.extra.releaseVersion,'16.6.6');assert.equal(app.expo.android.versionCode,31);assert.equal(app.expo.ios.buildNumber,'31');});
test('Web reference Settings source still matches the geometry targeted by Mobile',()=>{const css=readRoot('src/features/settings/settings.css');assert.match(css,/width:min\(100%,620px\)/);assert.match(css,/min-height:46px/);assert.match(css,/height:180px/);});