import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url));
const mobile=path.resolve(here,'..');
const read=(relative)=>fs.readFileSync(path.join(mobile,relative),'utf8');
const sharedTokens=fs.readFileSync(path.join(mobile,'../packages/alantil-ui/tokens.js'),'utf8');
const parity=read('ui/parity.js'),setPreparation=read('ui/set-preparation.js'),visual=read('ui/web-visual-source.js'),onboarding=read('screens/onboarding.js'),pathScreen=read('screens/path.js'),station=read('screens/station.js'),learn=read('screens/learn.js'),stationTest=read('screens/station-test.js'),practice=read('screens/practice.js'),practiceGames=read('screens/practice-games.js'),favorites=read('screens/favorites.js'),songs=read('screens/songs.js'),profile=read('screens/profile.js'),profileGate=read('screens/profile-gate.js'),profileMain=read('screens/profile-main.js'),appRoot=read('AppRoot.js');
const screenSources=[onboarding,pathScreen,station,learn,stationTest,practice,practiceGames,favorites,songs,profile,profileGate,profileMain];

test('16.3 exposes shared screen parity primitives',()=>{for(const name of['ScreenSection','SurfaceCard','CompactSegmentedControl','ListRow','MetricStrip','MonoLabel','EmptyState','OverflowMarquee'])assert.match(parity,new RegExp(`export function ${name}\\b`));});
test('onboarding consumes shared parity controls and shared setup core',()=>{assert.match(onboarding,/CompactSegmentedControl/);assert.match(onboarding,/LanguageSegmentedControl/);assert.match(onboarding,/DisclosureSection/);assert.match(onboarding,/completeLearningSetupSettings/);assert.match(onboarding,/previewCard/);assert.doesNotMatch(onboarding,/progressCell|setStep\(/);assert.match(onboarding,/visible=\{Boolean\(draft\.interface_language_code\)\}/);assert.match(onboarding,/visible=\{draft\.alan_script_code==='cyrillic'\}/);assert.doesNotMatch(onboarding,/function Segment\b/);});
test('path uses Web four-step route geometry and preserves progress core',()=>{assert.match(pathScreen,/POSITION_PATTERN\s*=\s*\[-1,\s*0,\s*1,\s*0\]/);assert.match(pathScreen,/scrollToEnd\(\{\s*animated:\s*false\s*\}\)/);assert.match(pathScreen,/createRouteProgressSnapshot/);assert.match(pathScreen,/stationWordProgress/);assert.match(sharedTokens,/scaleDot:4/);assert.match(sharedTokens,/scaleDiamond:9/);assert.match(pathScreen,/scaleDot:\s*\{[^}]*width:\s*theme\.path\.scaleDot[^}]*height:\s*theme\.path\.scaleDot/s);assert.match(pathScreen,/scaleDiamond:\s*\{[^}]*width:\s*theme\.path\.scaleDiamond[^}]*height:\s*theme\.path\.scaleDiamond/s);});
test('station keeps selection/favorites business state while using Web text tabs',()=>{assert.doesNotMatch(station,/CompactSegmentedControl value=\{pane\}/);assert.match(station,/stationTabTextActive/);assert.match(station,/SetPreparationView/);assert.match(station,/loadNativeHiddenWords/);assert.match(station,/toggleFavorite/);assert.match(station,/onLearn\(activeWords,\s*direction\)/);assert.match(station,/onTest\(station,\s*direction\)/);assert.match(station,/stats\.recent\.slice\(0,\s*3\)/);assert.match(station,/stats\.problems\.slice\(0,\s*7\)/);});
test('learn remains backed by shared learning core and resumable session storage',()=>{assert.match(learn,/initializeLearnState/);assert.match(learn,/decideLearnCard/);assert.match(learn,/undoLearnDecision/);assert.match(learn,/loadNativeSessionSnapshot\('learn'\)/);assert.match(learn,/saveNativeSessionSnapshot\('learn'/);assert.match(learn,/function LearningCard/);assert.match(learn,/MetricStrip/);});
test('station test remains backed by station-test core and snapshot recovery',()=>{assert.match(stationTest,/buildStationTestSessionState/);assert.match(stationTest,/stationTestActiveSnapshot/);assert.match(stationTest,/recordNativeTestSession/);assert.match(stationTest,/resultSummary/);assert.match(stationTest,/resultList/);assert.match(stationTest,/theme\.control\.header\+136/);});
test('practice and favorites consume the common flat list/control layer',()=>{assert.match(practice,/ListRow/);assert.match(practice,/panelHead/);assert.match(favorites,/SetPreparationView/);assert.match(setPreparation,/CompactSegmentedControl/);assert.match(setPreparation,/Checkbox/);assert.match(favorites,/loadNativeHiddenWords/);assert.match(favorites,/toggleFavorite/);assert.match(favorites,/showAll/);assert.match(favorites,/hideAll/);});
test('general Test and Match retain scope, limits and resumable shared-core sessions',()=>{assert.match(practiceGames,/\[20,\s*40,\s*80\]/);assert.match(practiceGames,/initializeTestState/);assert.match(practiceGames,/initializeMatchState/);assert.match(practiceGames,/loadNativeSessionSnapshot\('test'\)/);assert.match(practiceGames,/loadNativeSessionSnapshot\('match'\)/);});
test('songs remains isolated behind its platform adapter',()=>{assert.match(songs,/\.\.\/platform\/songs\.js/);});
test('profile setup stays inside Profile while Account remains the account owner',()=>{assert.match(profileGate,/ProfileMainArea/);assert.doesNotMatch(profileGate,/AccountScreen/);assert.match(profileMain,/if\(incomplete\)/);assert.match(profileMain,/ProfileSetup/);assert.match(profileMain,/avatarFrameLocked/);assert.match(profileMain,/dictionaryPathProgress/);assert.match(profileMain,/getNativeProgressSummary/);assert.match(profileMain,/settings\.versiya_prilozheniya/);});
test('screens never access Supabase directly',()=>{for(const source of screenSources)assert.doesNotMatch(source,/supabase-client|createClient\(|SUPABASE_URL|SUPABASE_ANON_KEY/);});
test('AppRoot retains main navigation round trips and safe-area contract',()=>{assert.match(appRoot,/StationScreen/);assert.match(appRoot,/LearnScreen/);assert.match(appRoot,/StationTestScreen/);assert.match(appRoot,/GeneralTestFlow/);assert.match(appRoot,/GeneralMatchFlow/);assert.match(appRoot,/FavoritesScreen/);assert.match(appRoot,/SongsScreen/);assert.match(appRoot,/AccountScreen/);assert.match(appRoot,/ProfileGate/);assert.match(appRoot,/theme\.safeArea\.shellEdges/);});
