import React, { useEffect, useMemo, useRef, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import { EVENTS } from '../packages/alantil-core/analytics.js';
import { buildLearningRoute } from '../packages/alantil-core/learning-route.js';
import { getDisplayedWordCollection } from '../packages/alantil-core/alan-display.js';
import { toggleFavorite } from '../packages/alantil-core/favorites.js';
import { DEFAULT_USER_SETTINGS, hasCompletedLearningSetup } from '../packages/alantil-core/settings.js';
import { msg } from './i18n.js';
import { BottomNav } from './ui/components.js';
import { RuntimeSettingsProvider } from './ui/runtime-settings.js';
import { theme } from './ui/theme.js';
import { AccountScreen } from './screens/profile.js';
import { ProfileGate } from './screens/profile-gate.js';
import { StationScreen } from './screens/station.js';
import { LearnScreen } from './screens/learn.js';
import { StationTestScreen } from './screens/station-test.js';
import { SongsScreen } from './screens/songs.js';
import { OnboardingScreen } from './screens/onboarding.js';
import { AuthChoiceScreen } from './screens/auth-choice.js';
import { PathScreen } from './screens/path.js';
import { StoryWordListScreen } from './screens/story-word-list.js';
import { PracticeScreen } from './screens/practice.js';
import { FavoritesScreen } from './screens/favorites.js';
import { GeneralMatchFlow, GeneralTestFlow } from './screens/practice-games.js';
import { bootstrapNativeAuth, subscribeNativeAuth } from './platform/auth.js';
import { trackNativeEvent, trackNativeScreen } from './platform/analytics.js';
import { synchronizeNativeAccount } from './platform/cloud-sync.js';
import { bootstrapNativeDictionary } from './platform/dictionary.js';
import { saveNativeActiveStory } from './platform/path-state.js';
import { setNativeSessionNamespace } from './platform/session-store.js';
import { hasCompletedNativeAuthChoice, loadNativeFavorites, loadNativeSettings, loadNativeSongFavorites, markNativeAuthChoiceComplete, saveNativeFavorites, saveNativeSettings, saveNativeSongFavorites } from './platform/storage.js';

const C=theme.colors;
function BootScreen(){return <View style={styles.boot}><Text style={styles.bootBrand}>Alan Til</Text><View style={styles.bootDot}/></View>;}
function settledValue(result,fallback){return result?.status==='fulfilled'?result.value:fallback;}
export default function AppRoot(){
  const [bootstrapped,setBootstrapped]=useState(false),[setupRequired,setSetupRequired]=useState(false),[authChoiceRequired,setAuthChoiceRequired]=useState(false),[words,setWords]=useState([]),[tab,setTab]=useState('path'),[screen,setScreen]=useState('home'),[favorites,setFavoritesState]=useState(()=>new Set()),[songFavorites,setSongFavoritesState]=useState(()=>new Set()),[settings,setSettingsState]=useState(()=>({...DEFAULT_USER_SETTINGS})),[station,setStation]=useState(null),[storyWordListType,setStoryWordListType]=useState(''),[learnContext,setLearnContext]=useState(null),[testContext,setTestContext]=useState(null),[practiceGameContext,setPracticeGameContext]=useState(null),[profileBottomNavVisible,setProfileBottomNavVisible]=useState(true),[dataEpoch,setDataEpoch]=useState(0);const displayWords=useMemo(()=>getDisplayedWordCollection(words,settings),[words,settings]),route=useMemo(()=>buildLearningRoute(displayWords),[displayWords]),authTransition=useRef(0),authUserId=useRef('');
  const hydrateScopedState=async()=>{const results=await Promise.allSettled([loadNativeSettings(),loadNativeFavorites(),loadNativeSongFavorites()]),savedSettings=settledValue(results[0],{...DEFAULT_USER_SETTINGS}),savedFavorites=settledValue(results[1],new Set()),savedSongFavorites=settledValue(results[2],new Set());setSettingsState(savedSettings||{...DEFAULT_USER_SETTINGS});setFavoritesState(savedFavorites instanceof Set?new Set(savedFavorites):new Set(savedFavorites||[]));setSongFavoritesState(savedSongFavorites instanceof Set?new Set(savedSongFavorites):new Set(savedSongFavorites||[]));setDataEpoch(value=>value+1);return savedSettings||{...DEFAULT_USER_SETTINGS};};
  const applyAuthTransition=async(session)=>{const nextUserId=String(session?.user?.id||'');if(nextUserId===authUserId.current)return;authUserId.current=nextUserId;const transition=++authTransition.current;if(session?.user){await synchronizeNativeAccount().catch(()=>false);}const scopedSettings=await hydrateScopedState();if(transition!==authTransition.current)return;const needsSetup=!session?.user&&!hasCompletedLearningSetup(scopedSettings),authChoiceDone=session?.user?true:Boolean(await hasCompletedNativeAuthChoice().catch(()=>false));if(session?.user)await markNativeAuthChoiceComplete().catch(()=>{});setSetupRequired(needsSetup);setAuthChoiceRequired(!session?.user&&!needsSetup&&!authChoiceDone);setTab('path');setScreen('home');setStation(null);setStoryWordListType('');setPracticeGameContext(null);};
  useEffect(()=>{let alive=true,unsubscribe=()=>{};(async()=>{try{const session=await bootstrapNativeAuth().catch(()=>null);authUserId.current=String(session?.user?.id||'');if(session?.user)await synchronizeNativeAccount().catch(()=>false);const bootstrapResults=await Promise.allSettled([Promise.allSettled([loadNativeSettings(),loadNativeFavorites(),loadNativeSongFavorites()]),bootstrapNativeDictionary(),hasCompletedNativeAuthChoice()]);const scopedResults=settledValue(bootstrapResults[0],[]),dictionaryResult=settledValue(bootstrapResults[1],null),authChoiceResult=Boolean(settledValue(bootstrapResults[2],false));if(!alive)return;const savedSettings=settledValue(scopedResults[0],{...DEFAULT_USER_SETTINGS}),savedFavorites=settledValue(scopedResults[1],new Set()),savedSongFavorites=settledValue(scopedResults[2],new Set()),needsSetup=!session?.user&&!hasCompletedLearningSetup(savedSettings||DEFAULT_USER_SETTINGS);setSettingsState(savedSettings||{...DEFAULT_USER_SETTINGS});setFavoritesState(savedFavorites instanceof Set?new Set(savedFavorites):new Set(savedFavorites||[]));setSongFavoritesState(savedSongFavorites instanceof Set?new Set(savedSongFavorites):new Set(savedSongFavorites||[]));setWords(Array.isArray(dictionaryResult?.words)?dictionaryResult.words:[]);setSetupRequired(needsSetup);setAuthChoiceRequired(!session?.user&&!needsSetup&&!authChoiceResult);setDataEpoch(1);setBootstrapped(true);void trackNativeEvent(EVENTS.APP_OPEN,{surface:'mobile'});}catch{if(!alive)return;setSettingsState({...DEFAULT_USER_SETTINGS});setFavoritesState(new Set());setSongFavoritesState(new Set());setWords([]);setSetupRequired(true);setAuthChoiceRequired(false);setBootstrapped(true);}unsubscribe=subscribeNativeAuth((session)=>{if(!alive)return;void applyAuthTransition(session||null);});})();return()=>{alive=false;authTransition.current+=1;unsubscribe();};},[]);
  useEffect(()=>{if(!bootstrapped)return;const name=setupRequired?'onboarding':authChoiceRequired?'auth_choice':tab==='path'?(screen==='home'?'path':screen):tab==='practice'?(screen==='home'?'practice':screen):screen==='home'?'profile':`profile_${screen}`;void trackNativeScreen(name,{tab,screen});},[bootstrapped,setupRequired,authChoiceRequired,tab,screen]);
  const setFavorites=(next)=>{const value=next instanceof Set?next:new Set(next||[]);setFavoritesState(new Set(value));saveNativeFavorites(value).catch(()=>{});};const setSongFavorites=(next)=>{const value=next instanceof Set?next:new Set(next||[]);setSongFavoritesState(new Set(value));saveNativeSongFavorites(value).catch(()=>{});};const setSettings=async(next)=>{const saved=await saveNativeSettings(next);setSettingsState(saved);return saved;};
  const changeTab=(next)=>{setTab(next);setScreen('home');setStation(null);setStoryWordListType('');setPracticeGameContext(null);setProfileBottomNavVisible(true);};const openStation=(nextStation)=>{setStation(nextStation);setScreen('station');};const backToPath=()=>{setScreen('home');setStation(null);};const openStoryWordList=(storyType)=>{setStoryWordListType(storyType);setScreen('storyWords');};const closeStoryWordList=()=>{setScreen('home');setStoryWordListType('');};const continueAsGuest=()=>{setTab('path');setScreen('home');setStation(null);};const completeAuthChoiceAsGuest=async()=>{await markNativeAuthChoiceComplete();setAuthChoiceRequired(false);continueAsGuest();};const completeAuthChoiceAsAccount=async()=>{await markNativeAuthChoiceComplete().catch(()=>{});};const openProfileStory=async(storyType)=>{if(!route.stories?.[storyType])return;await saveNativeActiveStory(storyType);setTab('path');setScreen('home');setStation(null);setStoryWordListType('');};
  const openPracticeGame=(type,sourceWords=displayWords,returnTo='home',scopeId='all')=>{setNativeSessionNamespace(type,scopeId);setPracticeGameContext({words:Array.isArray(sourceWords)?sourceWords:[],returnTo,scopeId});setScreen(type);};const closePracticeGame=()=>{const returnTo=practiceGameContext?.returnTo||'home';setPracticeGameContext(null);setScreen(returnTo);};
  const navLabels={practice:msg(settings,'nav.praktika'),path:msg(settings,'nav.put'),profile:msg(settings,'nav.profil')};
  const shell=(content,showNav=true)=><RuntimeSettingsProvider settings={settings}><SafeAreaProvider><StatusBar style="dark"/><SafeAreaView style={styles.safe} edges={theme.safeArea.shellEdges}><View style={styles.app}>{content}{showNav?<BottomNav tab={tab} onChange={changeTab} labels={navLabels}/>:null}</View></SafeAreaView></SafeAreaProvider></RuntimeSettingsProvider>;
  if(!bootstrapped)return shell(<BootScreen/>,false);
  if(setupRequired)return shell(<OnboardingScreen initialSettings={settings} onComplete={async(nextSettings)=>{const saved=await setSettings(nextSettings);if(!hasCompletedLearningSetup(saved))throw new Error('Learning setup was not persisted');setSetupRequired(false);setAuthChoiceRequired(true);}}/>,false);
  if(authChoiceRequired)return shell(<AuthChoiceScreen settings={settings} onAuthenticated={completeAuthChoiceAsAccount} onGuest={completeAuthChoiceAsGuest}/>,false);
  let content;let showNav=true;
  if(screen==='learn'&&learnContext){content=<LearnScreen words={learnContext.words} mode={learnContext.mode} station={learnContext.station} settings={settings} favorites={favorites} setFavorites={setFavorites} onBack={()=>setScreen(learnContext.returnTo||'station')}/>;showNav=false;}
  else if(screen==='stationTest'&&testContext){content=<StationTestScreen station={testContext.station} allWords={displayWords} mode={testContext.mode} settings={settings} favorites={favorites} setFavorites={setFavorites} onBack={()=>setScreen('station')}/>;showNav=false;}
  else if(tab==='path'&&screen==='storyWords'&&route.stories?.[storyWordListType]){content=<StoryWordListScreen story={route.stories[storyWordListType]} settings={settings} favorites={favorites} setFavorites={setFavorites} onBack={closeStoryWordList}/>;showNav=false;}
  else if(tab==='path'&&screen==='station'&&station){content=<StationScreen station={station} settings={settings} favorites={favorites} setFavorites={setFavorites} onBack={backToPath} onLearn={(rows,mode)=>{setLearnContext({words:rows,mode,station,returnTo:'station'});setScreen('learn');}} onTest={(target,mode)=>{setTestContext({station:target,mode});setScreen('stationTest');}}/>;showNav=false;}
  else if(tab==='practice'&&screen==='test'){const context=practiceGameContext||{words:displayWords,scopeId:'all'};content=<GeneralTestFlow words={context.words} settings={settings} favorites={favorites} setFavorites={setFavorites} onBack={closePracticeGame}/>;showNav=false;}
  else if(tab==='practice'&&screen==='match'){const context=practiceGameContext||{words:displayWords,scopeId:'all'};content=<GeneralMatchFlow words={context.words} settings={settings} favorites={favorites} setFavorites={setFavorites} onBack={closePracticeGame}/>;showNav=false;}
  else if(tab==='practice'&&screen==='favorites'){content=<FavoritesScreen words={displayWords} settings={settings} favorites={favorites} setFavorites={setFavorites} onBack={()=>setScreen('home')} onLearn={(rows,mode)=>{setLearnContext({words:rows,mode,station:null,returnTo:'favorites'});setScreen('learn');}}/>;showNav=false;}
  else if(tab==='practice'&&screen==='songs'){content=<SongsScreen words={displayWords} settings={settings} onBack={()=>setScreen('home')} favoriteIds={songFavorites} onFavorite={(id)=>setSongFavorites(toggleFavorite(songFavorites,id).ids)}/>;showNav=false;}
  else if(tab==='practice'){content=<PracticeScreen settings={settings} openTest={()=>openPracticeGame('test',displayWords,'home','all')} openMatch={()=>openPracticeGame('match',displayWords,'home','all')} openFavorites={()=>setScreen('favorites')} openSongs={()=>setScreen('songs')}/>;}
  else if(tab==='profile'&&screen==='account'){content=<AccountScreen settings={settings} onGuest={continueAsGuest} onBack={()=>setScreen('home')}/>;showNav=false;}
  else if(tab==='profile'){content=<ProfileGate key={`profile-${dataEpoch}`} words={displayWords} settings={settings} onSettingsChange={setSettings} onGuest={continueAsGuest} onOpenStory={openProfileStory} onBottomNavVisibilityChange={setProfileBottomNavVisible} onAccount={(action)=>{if(action==='open')setScreen('account');}}/>;showNav=profileBottomNavVisible;}
  else{content=<PathScreen key={`path-${dataEpoch}`} route={route} settings={settings} onOpenStation={openStation} onOpenWordList={openStoryWordList}/>;}
  return shell(content,showNav);
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:C.appBg},app:{flex:1,backgroundColor:C.appBg,overflow:'hidden'},boot:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:C.appBg},bootBrand:{fontSize:30,fontWeight:'900',color:C.text1},bootDot:{width:7,height:7,borderRadius:4,backgroundColor:C.accent,marginTop:18}});
