import React,{useEffect,useMemo,useState}from'react';
import{StyleSheet,View}from'react-native';
import{toggleFavorite}from'../../packages/alantil-core/favorites.js';
import{FAVORITES_HIDDEN_CONTEXT}from'../../packages/alantil-core/hidden-selection.js';
import{Button,Header,Screen}from'../ui/components.js';
import{EmptyState}from'../ui/parity.js';
import{SetPreparationView}from'../ui/set-preparation.js';
import{msg}from'../i18n.js';
import{loadNativeHiddenWords,saveNativeHiddenWords}from'../platform/hidden-words.js';
import{theme}from'../ui/theme.js';
export function FavoritesScreen({words,settings={},favorites,setFavorites,onBack,onLearn}){const m=(key,params)=>msg(settings,key,params),[hiddenIds,setHiddenIds]=useState(()=>new Set()),[direction,setDirection]=useState('kb'),[ready,setReady]=useState(false),rows=useMemo(()=>words.filter(word=>favorites.has(String(word.id))),[words,favorites]),activeRows=useMemo(()=>rows.filter(word=>!hiddenIds.has(String(word.id))),[rows,hiddenIds]);useEffect(()=>{let alive=true;loadNativeHiddenWords(FAVORITES_HIDDEN_CONTEXT).then(set=>{if(alive){setHiddenIds(set);setReady(true)}});return()=>{alive=false}},[]);const persist=(next,changed)=>{setHiddenIds(next);saveNativeHiddenWords(FAVORITES_HIDDEN_CONTEXT,next,changed).catch(()=>{})},toggleWord=id=>{const key=String(id),next=new Set(hiddenIds);if(next.has(key))next.delete(key);else next.add(key);persist(next,[key])},showAll=()=>{const next=new Set(hiddenIds),changed=rows.map(word=>String(word.id));changed.forEach(id=>next.delete(id));persist(next,changed)},hideAll=()=>{const next=new Set(hiddenIds),changed=rows.map(word=>String(word.id));changed.forEach(id=>next.add(id));persist(next,changed)},unfavorite=word=>{const key=String(word.id),nextHidden=new Set(hiddenIds);nextHidden.delete(key);persist(nextHidden,[key]);setFavorites(toggleFavorite(favorites,word.id).ids)};return <Screen topChromeDepth={theme.chrome.screenDepths.setPreparation.top} bottomChromeDepth={theme.chrome.screenDepths.setPreparation.bottom}><Header title={m('mobile.practice.favorites')} subtitle={m('mobile.common.words_count',{count:rows.length})} onBack={onBack}/>{rows.length?<SetPreparationView rows={rows} hiddenIds={hiddenIds} ready={ready} settings={settings} onToggle={toggleWord} onShowAll={showAll} onHideAll={hideAll} isFavorite={()=>true} onFavorite={unfavorite} direction={direction} onDirectionChange={setDirection} footerChildren={<Button role="favorites.start" style={styles.start} disabled={!activeRows.length} onPress={()=>onLearn(activeRows,direction)}>{m('mobile.station.learn')}</Button>}/>:<View style={styles.empty}><EmptyState>{m('mobile.favorites.empty')}</EmptyState></View>}</Screen>}
const styles=StyleSheet.create({start:{width:'100%'},empty:{flex:1,marginTop:theme.control.header+24,marginHorizontal:14,justifyContent:'center'}});