import React, { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { Button, Header, Screen } from '../ui/components.js';
import { Checkbox } from '../ui/checkbox.js';
import { msg } from '../i18n.js';
import { useSemanticTypography } from '../ui/runtime-settings.js';
import { theme } from '../ui/theme.js';
import { loadNativeAnalyticsPreference, saveNativeAnalyticsPreference } from '../platform/privacy.js';

const C=theme.colors;
function Document({children}){return <ScrollView contentContainerStyle={styles.document} showsVerticalScrollIndicator={false}>{children}</ScrollView>;}
function H2({children,type}){return <Text style={[styles.h2,type.emphasis]}>{children}</Text>;}
function P({children,type}){return <Text style={[styles.p,type.body]}>{children}</Text>;}
function Thanks({settings,type}){return <Document><Text style={[styles.h1,type.title]}>{msg(settings,'about.blagodarstvennoe_slovo')}</Text><P type={type}>{msg(settings,'about.zdes_budet_razmeschena_blagodarnost_lyudyam_kotorye_pomoga')}</P></Document>;}
function Version({settings,type}){return <Document><View style={styles.fact}><Text style={[styles.factLabel,type.body]}>{msg(settings,'about.versiya')}</Text><Text style={[styles.factValue,type.caption]}>16.6.6</Text></View><View style={styles.fact}><Text style={[styles.factLabel,type.body]}>{msg(settings,'about.poslednee_obnovlenie')}</Text><Text style={[styles.factValue,type.caption]}>06.09.2026</Text></View></Document>;}
function Privacy({settings,type}){
  const [enabled,setEnabled]=useState(false),[loaded,setLoaded]=useState(false),[saved,setSaved]=useState(false);
  useEffect(()=>{let alive=true;loadNativeAnalyticsPreference().then((value)=>{if(alive){setEnabled(value===true);setLoaded(true);}});return()=>{alive=false;};},[]);
  const save=async()=>{await saveNativeAnalyticsPreference(enabled);setSaved(true);};
  const h=(children)=><H2 type={type}>{children}</H2>,p=(children)=><P type={type}>{children}</P>;
  return <Document>{p(<><Text style={styles.strong}>{msg(settings,'privacy.alantil_alan_til')} </Text>{msg(settings,'privacy.prilozhenie_dlya_izucheniya_karachaevo_balkarskogo_yazyka_')} alantil0709@gmail.com.</>)}{h(msg(settings,'privacy.kakie_dannye_sohranyayutsya_na_ustroystve'))}{p(msg(settings,'privacy.prilozhenie_mozhet_lokalno_sohranyat_v_brauzere_izbrannye'))}{h(msg(settings,'privacy.akkaunt_i_avtorizatsiya'))}{p(msg(settings,'privacy.registratsiya_neobyazatelna_pri_vhode_cherez_google_parol'))}{h(msg(settings,'privacy.oblachnyy_progress'))}{p(msg(settings,'privacy.dlya_avtorizovannogo_polzovatelya_supabase_mozhet_hranit_i'))}{h(msg(settings,'privacy.visit_activity_title'))}{p(msg(settings,'privacy.visit_activity_text'))}{h(msg(settings,'privacy.kakie_dannye_peredayutsya_v_google_analytics'))}{p(msg(settings,'privacy.pri_vklyuchennoy_statistike_mogut_peredavatsya_prosmotry_r'))}{h(msg(settings,'privacy.kakie_dannye_ne_peredayutsya_v_google_analytics'))}{p(msg(settings,'privacy.prilozhenie_ne_peredaet_v_google_analytics_nikneym'))}{h(msg(settings,'privacy.zachem_ispolzuetsya_analitika'))}{p(msg(settings,'privacy.analitika_pomogaet_ponimat_kak_primenyayutsya_razdely_pril'))}{h(msg(settings,'privacy.udalenie_dannyh'))}{p(msg(settings,'privacy.lokalnye_dannye_mozhno_udalit_cherez_ochistku_dannyh'))}<View style={styles.analytics}>{h(msg(settings,'privacy.statistika_ispolzovaniya'))}{p(msg(settings,'privacy.statistika_ispolzovaniya_pomogaet_nam_uluchshat_prilozheni'))}<View style={styles.switchRow}><Text style={[styles.switchLabel,type.body]}>{msg(settings,'privacy.razreshit_statistiku_ispolzovaniya')}</Text><Checkbox size={20} disabled={!loaded} checked={enabled} accessibilityLabel={msg(settings,'privacy.razreshit_statistiku_ispolzovaniya')} onPress={()=>{setSaved(false);setEnabled((value)=>!value);}}/></View><Button role="privacy.save" onPress={save}>{saved?msg(settings,'privacy.nastroyki_statistiki_sohraneny'):msg(settings,'privacy.sohranit_nastroyki')}</Button></View>{p(msg(settings,'privacy.revision_august_2026'))}</Document>;
}
export function SettingsChildScreen({screen,settings,onBack}){const type=useSemanticTypography(),title=screen==='thanks'?msg(settings,'about.blagodarnosti'):screen==='version'?msg(settings,'about.versiya_prilozheniya'):msg(settings,'privacy.konfidentsialnost');return <Screen><Header title={title} onBack={onBack}/>{screen==='thanks'?<Thanks settings={settings} type={type}/>:screen==='version'?<Version settings={settings} type={type}/>:<Privacy settings={settings} type={type}/>}</Screen>;}
const styles=StyleSheet.create({document:{paddingTop:theme.control.header+theme.chrome.contentRestGap,paddingHorizontal:16,paddingBottom:30,gap:12},h1:{color:C.text1,marginBottom:4},h2:{color:C.text1,marginTop:8},p:{color:C.text2},strong:{fontWeight:'800',color:C.text1},fact:{minHeight:46,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:C.lineSoft},factLabel:{color:C.text2},factValue:{fontFamily:theme.font.terminal,fontWeight:'700',color:C.text1},analytics:{gap:10,marginTop:8,paddingTop:8,borderTopWidth:1,borderTopColor:C.lineSoft},switchRow:{minHeight:46,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:C.lineSoft},switchLabel:{flex:1,color:C.text1}});