import React, { useEffect, useMemo, useRef, useState } from 'react';
import { BackHandler, ScrollView, StyleSheet, Text, View } from 'react-native';
import { applyStationTestAnswer, buildStationTestSessionState, stationTestActiveSnapshot, stationTestPayload, stationTestResult } from '../../packages/alantil-core/station-test.js';
import { toggleFavorite } from '../../packages/alantil-core/favorites.js';
import { Button, FavoriteButton, Header, OptionChoice, Screen } from '../ui/components.js';
import { useSessionExit } from '../ui/session-exit.js';
import { FadedScrollView } from '../ui/faded-scroll';
import { CorrectIcon, WrongIcon } from '../ui/icons.js';
import { EmptyState, OverflowMarquee } from '../ui/parity.js';
import { useMobileMsg, useRuntimeSettings, useSemanticTypography } from '../ui/runtime-settings.js';
import { theme } from '../ui/theme.js';
import { recordNativeTestSession } from '../platform/progress.js';
import { clearNativeSessionSnapshot, loadNativeSessionSnapshot, saveNativeSessionSnapshot } from '../platform/session-store.js';

const C=theme.colors;
function ResultText({children,style,containerStyle}){return <OverflowMarquee style={containerStyle} textStyle={style}>{children}</OverflowMarquee>;}

export function StationTestScreen({station,allWords,mode='kb',favorites=new Set(),setFavorites=()=>{},onBack}){
  const m=useMobileMsg(),{settings}=useRuntimeSettings(),type=useSemanticTypography();
  const [session,setSession]=useState(null),[selectedId,setSelectedId]=useState('');const [,redraw]=useState(0),recorded=useRef(false);
  const createSession=(interrupted=null)=>buildStationTestSessionState({station,optionWords:allWords,mode,interrupted,id:`station-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,startedAt:new Date().toISOString()});
  useEffect(()=>{let alive=true;(async()=>{const interrupted=await loadNativeSessionSnapshot('station-test'),next=createSession(interrupted);if(alive)setSession(next);})();return()=>{alive=false;};},[station,allWords,mode]);
  const question=session?.questions?.[session.index],done=Boolean(session&&!question),result=useMemo(()=>done?stationTestResult(session,stationTestPayload(session)):null,[done,session]);
  useEffect(()=>{setSelectedId('');},[session?.index]);
  useEffect(()=>{if(!done||!result||recorded.current)return;recorded.current=true;session.completed=true;const payload=stationTestPayload(session);recordNativeTestSession({sessionId:session.id,answers:payload.words.map((row)=>({word_id:row.word_id,result:row.result})),accuracy:payload.accuracy,requiredAccuracy:payload.required_accuracy,updateMastery:true,startedAt:session.startedAt,type:'station_test',stationKey:station?.key||'',phase:payload.phase||session.phase||''}).catch(()=>{});clearNativeSessionSnapshot('station-test').catch(()=>{});},[done,result,session,station?.key]);
  const exit=useSessionExit({active:Boolean(session&&!session.completed&&!done),save:()=>saveNativeSessionSnapshot('station-test',stationTestActiveSnapshot(session)),onLeave:onBack});const back=exit.request;
  const retry=async()=>{await clearNativeSessionSnapshot('station-test').catch(()=>{});recorded.current=false;setSelectedId('');const next=createSession(null);setSession(next);redraw((value)=>value+1);saveNativeSessionSnapshot('station-test',stationTestActiveSnapshot(next)).catch(()=>{});};
  useEffect(()=>{const sub=BackHandler.addEventListener('hardwareBackPress',()=>{back();return true;});return()=>sub.remove();},[session,onBack]);
  if(!session)return <Screen><Header title={m('mobile.test.title')} subtitle={station?.name||''} onBack={onBack}/><View style={styles.center}><EmptyState>{m('mobile.stage.restoring')}</EmptyState></View></Screen>;
  if(done&&result){const levelSymbol=result.masteryLevel?'⌃'.repeat(result.masteryLevel):'—';return <Screen topChromeDepth={theme.chrome.screenDepths.testResults.top} bottomChromeDepth={theme.chrome.screenDepths.testResults.bottom}><Header title={m('mobile.stage.results')} subtitle={station?.name||''} onBack={onBack}/><View style={styles.resultView}><View style={styles.resultSummary}><Text style={styles.resultMark}>{levelSymbol}</Text><Text style={[styles.resultScore,type.result,result.passed?styles.scorePassed:styles.scoreFailed]}>{result.payload.accuracy}%</Text><Text style={[styles.resultStatus,type.caption]}>{result.passed?m('mobile.stage.passed'):m('mobile.stage.repeat')} · {result.payload.correct_total}/{result.payload.questions_total}</Text></View><FadedScrollView topFade={theme.chrome.scrollFades.testResults.top} bottomFade={theme.chrome.scrollFades.testResults.bottom} contentContainerStyle={styles.resultList} showsVerticalScrollIndicator={false}>{session.answers.map((answer,index)=>{const source=session.questions[index],correct=answer.result==='correct',selected=source?.options?.find((option)=>String(option.id)===String(answer.wrongWordId||source?.item?.id)),wordId=String(answer.wordId||source?.item?.id||''),primary=session.mode==='ru'?source?.item?.trans:source?.item?.word,correctAnswer=session.mode==='ru'?source?.item?.word:source?.item?.trans;return <View key={`${wordId}-${index}`} style={styles.resultRow}><View style={[styles.resultDot,correct?styles.resultDotCorrect:styles.resultDotWrong]}>{correct?<CorrectIcon size={16} color={C.successStrong}/>:<WrongIcon size={16} color={C.dangerStrong}/>}</View><View style={styles.resultCopy}><ResultText style={[styles.resultPrimary,type.emphasis]}>{primary}</ResultText>{!correct?<View style={styles.detailLine}><Text style={styles.detailLabel}>{m('mobile.common.your_answer')}</Text><ResultText containerStyle={styles.detailValue} style={[styles.resultWrong,type.micro]}>{selected?.text||'—'}</ResultText></View>:null}<View style={styles.detailLine}><Text style={styles.detailLabel}>{m('mobile.common.correct')}</Text><ResultText containerStyle={styles.detailValue} style={[styles.resultCorrect,type.micro]}>{correctAnswer}</ResultText></View></View><FavoriteButton active={favorites.has(wordId)} onPress={()=>setFavorites(toggleFavorite(favorites,wordId).ids)}/></View>;})}</FadedScrollView><View style={styles.footer}><View style={styles.footerButton}><Button role="path.resultBack" onPress={onBack}>{m('mobile.stage.to_station')}</Button></View>{!result.passed?<View style={styles.footerButton}><Button role="test.retry" onPress={retry}>{m('mobile.common.retry')}</Button></View>:null}</View></View></Screen>;}
  const prompt=session.mode==='ru'?question.item.trans:question.item.word;
  const submit=()=>{if(!selectedId)return;applyStationTestAnswer(session,selectedId);saveNativeSessionSnapshot('station-test',stationTestActiveSnapshot(session)).catch(()=>{});setSelectedId('');setSession(session);redraw((value)=>value+1);};
  return <Screen topChromeDepth={theme.chrome.screenDepths.testSession.top} bottomChromeDepth={theme.chrome.screenDepths.testSession.bottom}>{exit.dialog}<Header title={m('mobile.test.title')} subtitle={station?.name||''} onBack={back} sessionStatus={{counter:`${session.index+1}/${session.questions.length}`,mode:mode==='ru'?m('mobile.common.ru_alan').toUpperCase():m('mobile.common.alan_ru').toUpperCase()}}/><View style={styles.testView}><FadedScrollView topFade={theme.chrome.screenDepths.testSession.top} bottomFade={theme.chrome.screenDepths.testSession.bottom} contentContainerStyle={styles.testScroll} showsVerticalScrollIndicator={false}><View style={styles.promptBlock}><Text style={[styles.prompt,type.display]}>{prompt}</Text></View><View style={styles.options}>{question.options.map((option)=>{const selected=selectedId===String(option.id);return <OptionChoice key={`${question.item.id}-${option.id}`} selected={selected} onPress={()=>setSelectedId(String(option.id))} labelStyle={type.emphasis}>{option.text}</OptionChoice>;})}</View></FadedScrollView><View style={styles.answerBar}><View style={styles.answerButton}><Button role="test.submit" disabled={!selectedId} onPress={submit}>{m('mobile.common.answer')}</Button></View></View></View></Screen>;
}

const styles=StyleSheet.create({center:{flex:1,justifyContent:'center',paddingHorizontal:20},testView:{flex:1,paddingTop:theme.control.header+theme.chrome.contentRestGap,paddingHorizontal:14,paddingBottom:theme.chrome.actionEdgeGap},testScroll:{flexGrow:1,paddingTop:4,paddingBottom:70,gap:12},promptBlock:{flexGrow:1,minHeight:150,maxWidth:520,width:'100%',alignSelf:'center',alignItems:'center',justifyContent:'center',paddingHorizontal:22},prompt:{color:C.text1,textAlign:'center'},options:{width:'100%',maxWidth:520,alignSelf:'center',gap:8},answerBar:{position:'absolute',zIndex:30,elevation:30,left:14,right:14,bottom:theme.chrome.actionEdgeGap,alignItems:'flex-end'},answerButton:{width:180,maxWidth:'52%'},resultView:{flex:1},resultSummary:{position:'absolute',zIndex:30,elevation:30,top:theme.control.header+4,left:14,right:14,height:116,minHeight:116,padding:8,borderBottomWidth:1,borderBottomColor:C.lineSoft,alignItems:'center',justifyContent:'center'},resultMark:{fontFamily:theme.font.terminal,fontSize:18,fontWeight:'900',color:C.accentStrong,textAlign:'center'},resultScore:{fontFamily:theme.font.terminal,textAlign:'center',marginTop:3},scorePassed:{color:C.successStrong},scoreFailed:{color:C.dangerStrong},resultStatus:{color:C.text2,textAlign:'center',marginTop:6},resultList:{paddingTop:theme.control.header+136,paddingHorizontal:14,paddingBottom:70},resultRow:{minHeight:62,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1,borderBottomColor:C.lineSoft,paddingVertical:7},resultDot:{width:24,height:24,borderRadius:12,borderWidth:1,alignItems:'center',justifyContent:'center'},resultDotCorrect:{borderColor:C.success,backgroundColor:C.successSoft},resultDotWrong:{borderColor:C.danger,backgroundColor:C.dangerSoft},resultCopy:{flex:1,minWidth:0,gap:3},resultPrimary:{color:C.text1},detailLine:{width:'100%',flexDirection:'row',alignItems:'center',gap:5},detailLabel:{fontFamily:theme.font.terminal,fontSize:9,fontWeight:'800',lineHeight:11,color:C.text3},detailValue:{flex:1,minWidth:0,width:undefined},resultWrong:{color:C.dangerStrong},resultCorrect:{color:C.successStrong},footer:{position:'absolute',zIndex:30,elevation:30,left:14,right:14,bottom:theme.chrome.actionEdgeGap,flexDirection:'row',justifyContent:'flex-end',gap:8},footerButton:{width:176,maxWidth:'48%'}});
