import AsyncStorage from '@react-native-async-storage/async-storage';
import * as WebBrowser from 'expo-web-browser';
import { AppState, Linking } from 'react-native';
import { setNativeStorageScope } from './storage-scope.js';
import { NATIVE_SUPABASE_PUBLISHABLE_KEY, NATIVE_SUPABASE_URL, nativeSupabase } from './supabase.native.js';

export const NATIVE_AUTH_REDIRECT_URL='alantil://auth/callback';
const SESSION_KEY='alantil:16.1:auth-session';
const listeners=new Set();
let currentSession=null,initialized=false,syncStartedForUser='',lastAuthError=null,bootstrapPromise=null,refreshPromise=null,callbackPromise=null,oauthFlowPromise=null,lastHandledCallbackUrl='',authSubscription=null,appStateSubscription=null,linkSubscription=null;

function emit(){listeners.forEach((listener)=>{try{listener(currentSession,lastAuthError);}catch{}});}
function setAuthError(error){lastAuthError=error||null;emit();return lastAuthError;}
function normalizeSession(session){if(!session)return null;const rawExpiresAt=Number(session.expires_at||0),expiresAt=rawExpiresAt&&rawExpiresAt<1e12?rawExpiresAt*1000:rawExpiresAt;return {...session,expires_at:expiresAt||0};}
async function triggerAccountSync(){const userId=String(currentSession?.user?.id||'');if(!userId||syncStartedForUser===userId)return;syncStartedForUser=userId;try{const {synchronizeNativeAccount}=await import('./cloud-sync.js');await synchronizeNativeAccount();}catch{syncStartedForUser='';}}
function callbackParams(url){const value=String(url||'');if(!value.startsWith(NATIVE_AUTH_REDIRECT_URL))return null;const parsed=new URL(value),query=new URLSearchParams(parsed.search||''),hash=new URLSearchParams(String(parsed.hash||'').replace(/^#/,'')),read=(key)=>String(hash.get(key)||query.get(key)||'').trim(),oauthError=read('error_description')||read('error')||read('error_code');if(oauthError){const error=new Error(oauthError);error.code='OAUTH_CALLBACK_ERROR';throw error;}return {code:read('code'),flowId:read('sb_flow_id'),accessToken:read('access_token'),refreshToken:read('refresh_token')};}
async function persist(session){currentSession=normalizeSession(session);setNativeStorageScope(currentSession?.user?.id||'');lastAuthError=null;if(currentSession)await AsyncStorage.setItem(SESSION_KEY,JSON.stringify(currentSession));else{await AsyncStorage.removeItem(SESSION_KEY);syncStartedForUser='';lastHandledCallbackUrl='';}emit();void triggerAccountSync();return currentSession;}
async function dismissAuthBrowser(){try{await WebBrowser.dismissBrowser();}catch{}try{WebBrowser.dismissAuthSession();}catch{}}
async function sessionFromCallback(params){if(params?.code){const options=params.flowId?{flowId:params.flowId}:undefined,{data,error}=await nativeSupabase.auth.exchangeCodeForSession(params.code,options);if(error)throw error;if(!data?.session?.user)throw new Error('Authenticated session was not returned after PKCE exchange');return data.session;}if(params?.accessToken||params?.refreshToken){if(!params.accessToken||!params.refreshToken)throw new Error('OAuth callback did not include both access and refresh tokens');const {data,error}=await nativeSupabase.auth.setSession({access_token:params.accessToken,refresh_token:params.refreshToken});if(error)throw error;if(!data?.session?.user)throw new Error('Authenticated session was not returned after token callback');return data.session;}const {data,error}=await nativeSupabase.auth.getSession();if(error)throw error;if(data?.session?.user)return data.session;throw new Error('OAuth callback did not include a PKCE code or session tokens');}
async function restoreLegacySession(){let raw='';try{raw=await AsyncStorage.getItem(SESSION_KEY);}catch{return null;}if(!raw)return null;let legacy=null;try{legacy=JSON.parse(raw);}catch{await AsyncStorage.removeItem(SESSION_KEY);return null;}if(!legacy?.access_token||!legacy?.refresh_token){await AsyncStorage.removeItem(SESSION_KEY);return null;}try{const {data,error}=await nativeSupabase.auth.setSession({access_token:legacy.access_token,refresh_token:legacy.refresh_token});if(error)throw error;if(!data?.session?.user)throw new Error('Legacy session could not be restored');return data.session;}catch{await AsyncStorage.removeItem(SESSION_KEY);return null;}}
function bindNativeAuthEvents(){if(!authSubscription){const {data}=nativeSupabase.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){persist(null).catch(()=>{});return;}if(session?.user)persist(session).catch((error)=>setAuthError(error));});authSubscription=data?.subscription||null;}if(!linkSubscription)linkSubscription=Linking.addEventListener('url',({url})=>{handleNativeAuthUrl(url).catch(()=>{});});if(!appStateSubscription){if(AppState.currentState==='active')nativeSupabase.auth.startAutoRefresh();appStateSubscription=AppState.addEventListener('change',(state)=>{if(state==='active'){nativeSupabase.auth.startAutoRefresh();ensureFreshSession().then(()=>triggerAccountSync()).catch(()=>{});}else nativeSupabase.auth.stopAutoRefresh();});}}

export async function refreshNativeAuthSession({clearOnFailure=true}={}){if(refreshPromise)return refreshPromise;if(!currentSession?.refresh_token)return currentSession;refreshPromise=(async()=>{try{const {data,error}=await nativeSupabase.auth.refreshSession({refresh_token:currentSession.refresh_token});if(error)throw error;if(!data?.session?.user)throw new Error('Session refresh returned no session');return await persist(data.session);}catch(error){if(clearOnFailure){try{await nativeSupabase.auth.signOut({scope:'local'});}catch{}await persist(null);}setAuthError(error);throw error;}})().finally(()=>{refreshPromise=null;});return refreshPromise;}
async function ensureFreshSession(){if(currentSession?.expires_at&&currentSession.expires_at<=Date.now()+60000)await refreshNativeAuthSession();return currentSession;}
export async function handleNativeAuthUrl(url){const value=String(url||'');if(!value.startsWith(NATIVE_AUTH_REDIRECT_URL))return currentSession;if(value===lastHandledCallbackUrl&&currentSession?.user)return currentSession;if(callbackPromise)return callbackPromise;callbackPromise=(async()=>{try{const params=callbackParams(value),session=await sessionFromCallback(params);const saved=await persist(session);lastHandledCallbackUrl=value;return saved;}catch(error){setAuthError(error);throw error;}finally{await dismissAuthBrowser();}})().finally(()=>{callbackPromise=null;});return callbackPromise;}
async function bootstrapImpl(){if(!initialized){initialized=true;bindNativeAuthEvents();}
  try{const initialUrl=await Linking.getInitialURL();if(initialUrl?.startsWith(NATIVE_AUTH_REDIRECT_URL))await handleNativeAuthUrl(initialUrl);}catch(error){setAuthError(error);}
  if(!currentSession){try{const {data,error}=await nativeSupabase.auth.getSession();if(error)throw error;if(data?.session?.user)await persist(data.session);}catch(error){setAuthError(error);}}
  if(!currentSession){const restored=await restoreLegacySession();if(restored)await persist(restored);}
  if(currentSession?.expires_at&&currentSession.expires_at<=Date.now()+60000){try{await refreshNativeAuthSession();}catch{}}
  if(currentSession?.access_token&&!currentSession.user){try{const {data,error}=await nativeSupabase.auth.getUser(currentSession.access_token);if(error)throw error;if(!data?.user)throw new Error('Authenticated user was not returned');currentSession={...currentSession,user:data.user};await persist(currentSession);}catch(error){await persist(null);setAuthError(error);}}
  setNativeStorageScope(currentSession?.user?.id||'');void triggerAccountSync();emit();return currentSession;
}
export async function bootstrapNativeAuth(){if(!bootstrapPromise)bootstrapPromise=bootstrapImpl().finally(()=>{bootstrapPromise=null;});return bootstrapPromise;}
export function subscribeNativeAuth(listener){listeners.add(listener);return()=>listeners.delete(listener);}
export function getNativeAuthSession(){return currentSession;}
export function getNativeAuthError(){return lastAuthError;}
export function getNativeAuthProvider(session=currentSession){const user=session?.user;if(!user)return '';return String(user?.app_metadata?.provider||user?.identities?.[0]?.provider||user?.user_metadata?.provider||'').trim().toLowerCase();}
export async function signInWithGoogleNative(){if(oauthFlowPromise)return oauthFlowPromise;lastAuthError=null;emit();oauthFlowPromise=(async()=>{try{const {data,error}=await nativeSupabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:NATIVE_AUTH_REDIRECT_URL,skipBrowserRedirect:true,queryParams:{prompt:'select_account'}}});if(error)throw error;if(!data?.url)throw new Error('Supabase did not return a Google OAuth URL');const result=await WebBrowser.openAuthSessionAsync(data.url,NATIVE_AUTH_REDIRECT_URL,{showInRecents:true});if(result?.type==='success'&&result.url)return await handleNativeAuthUrl(result.url);if(result?.type==='cancel'||result?.type==='dismiss')return currentSession;return currentSession;}catch(error){setAuthError(error);throw error;}})().finally(()=>{oauthFlowPromise=null;});return oauthFlowPromise;}
export async function signOutNative(){let error=null;try{const result=await nativeSupabase.auth.signOut({scope:'local'});error=result?.error||null;}catch(nextError){error=nextError;}await persist(null);if(error){setAuthError(error);throw error;}return null;}
async function authorizedRequest(path,options,session){const headers={apikey:NATIVE_SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json',...(session?.access_token?{Authorization:`Bearer ${session.access_token}`} :{}),...(options.headers||{})};return fetch(`${NATIVE_SUPABASE_URL}${path}`,{...options,headers});}
export async function nativeAuthFetch(path,options={}){await bootstrapNativeAuth();await ensureFreshSession();let response=await authorizedRequest(path,options,currentSession);if(response.status===401&&currentSession?.refresh_token){await refreshNativeAuthSession();response=await authorizedRequest(path,options,currentSession);}return response;}
